name: Enforce Branch Flow
on:
  pull_request:
    branches: [ main, integration, production ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate base/head
        run: |
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.head_ref }}"

          # Protected env branches
          PROTECTED_MAIN="development"
          PROTECTED_INT="integration"
          PROTECTED_PROD="production"

          # Allowed flows:
          # 1) feature/* (or any non-protected)  -> development
          # 2) development                       -> integration
          # 3) integration                       -> production

          if { [ "$BASE" = "$PROTECTED_MAIN" ] \
               && [ "$HEAD" != "$PROTECTED_MAIN" ] \
               && [ "$HEAD" != "$PROTECTED_INT" ] \
               && [ "$HEAD" != "$PROTECTED_PROD" ]; }; then
            echo "Flow OK: $HEAD -> $BASE"
            exit 0
          fi

          if { [ "$BASE" = "$PROTECTED_INT" ] && [ "$HEAD" = "$PROTECTED_MAIN" ]; }; then
            echo "Flow OK: $HEAD -> $BASE"
            exit 0
          fi

          if { [ "$BASE" = "$PROTECTED_PROD" ] && [ "$HEAD" = "$PROTECTED_INT" ]; }; then
            echo "Flow OK: $HEAD -> $BASE"
            exit 0
          fi

          echo "::error ::Invalid branch flow: $HEAD -> $BASE. Allowed: feature→main, main→integration, integration→production."
          exit 1